language: node_js

dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable

node_js:
  - "6.9.1"

sudo: false

branches:
   only:
   - master

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script: yarn test
