language: node_js

dist: trusty

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

node_js:
  - 8

sudo: false

branches:
   only:
   - master

cache:
  yarn: true
  directories:
    - node_modules

# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - yarn

script: yarn test
